kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "secret-transform.name" . }}
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "secret-transform.name" . }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "secret-transform.name" . }}
    namespace: {{ .Release.Namespace }}
